
# docker compose up -d
# docker compose run sipbp test
# docker compose run sipbp createsuperuser --username root --no-input
services:
  sipbp:
    build: .
    container_name: si-pbp
    ports:
      - "8000:8000"
    expose:
      - "8000"
    restart: unless-stopped
    env_file: .env
  bot:
    build: .
    container_name: si-bot
    restart: unless-stopped
    env_file: .env
    entrypoint: run-bot.sh
  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    restart: always
    env_file: .env
    volumes:
      - cache:/data

volumes:
  app:
  cache:
    driver: local